# Generated by Django 5.2.1 on 2025-12-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(blank=True, help_text='프로필 이미지', null=True, upload_to='profiles/'),
        ),
    ]
