# Generated by Django 5.2.1 on 2025-11-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='charts',
            field=models.ManyToManyField(blank=True, help_text='사용자가 만든 차트들 (커뮤니티 곡)', related_name='creators', to='game.chart'),
        ),
    ]
