# Generated by Django 5.2.1 on 2025-11-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_charts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='charts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='high_score',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='사용자 이름', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='사용자 이메일', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='비밀번호', max_length=128),
        ),
    ]
