# Generated by Django 5.2.8 on 2025-11-30 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicId', models.CharField(help_text='곡 ID', max_length=100, unique=True)),
                ('title', models.CharField(help_text='곡 제목', max_length=200)),
                ('song', models.CharField(help_text='노래 음원 파일 경로', max_length=500)),
                ('backgroundVideo', models.CharField(help_text='백그라운드 비디오 파일 경로', max_length=500)),
                ('coverUrl', models.CharField(help_text='커버 이미지 URL', max_length=500)),
                ('isCommunitySong', models.BooleanField(default=False, help_text='커뮤니티 곡 여부')),
                ('artist', models.CharField(help_text='아티스트명', max_length=200)),
                ('difficulty', models.IntegerField(help_text='난이도 (1~15)')),
                ('creator', models.ForeignKey(help_text='차트를 만든 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='charts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(help_text='노트 ID', primary_key=True, serialize=False)),
                ('time', models.IntegerField(help_text='노트가 내려올 시간 (ms 단위)')),
                ('lane', models.IntegerField(help_text='노트의 라인 위치')),
                ('type', models.CharField(choices=[('tap', 'Tap'), ('hold', 'Hold')], help_text='노트 타입', max_length=10)),
                ('duration', models.IntegerField(blank=True, help_text='홀드 노트의 유지 시간 (ms 단위)', null=True)),
                ('chart', models.ForeignKey(help_text='노트가 속한 차트', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='game.chart')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicId', models.CharField(help_text='곡 ID', max_length=100)),
                ('difficulty', models.IntegerField(help_text='플레이한 난이도')),
                ('score', models.IntegerField(help_text='최종 점수')),
                ('accuracy', models.FloatField(help_text='정확도 (%)')),
                ('rank', models.CharField(choices=[('F', 'F'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S'), ('SS', 'SS')], help_text='점수 기반 랭크', max_length=2)),
                ('combo', models.CharField(help_text='콤보 기록 (문자열)', max_length=500)),
                ('isFullCombo', models.BooleanField(default=False, help_text='풀콤보 여부')),
                ('isAllPerfect', models.BooleanField(default=False, help_text='올 퍼펙트 여부')),
                ('earlyCount', models.IntegerField(default=0, help_text='빠르게 친 판정 수')),
                ('lateCount', models.IntegerField(default=0, help_text='느리게 친 판정 수')),
                ('perfect', models.IntegerField(default=0, help_text='퍼펙트 판정 수')),
                ('great', models.IntegerField(default=0, help_text='그레이트 판정 수')),
                ('good', models.IntegerField(default=0, help_text='굿 판정 수')),
                ('miss', models.IntegerField(default=0, help_text='미스 판정 수')),
                ('bad', models.IntegerField(default=0, help_text='배드 판정 수')),
                ('playedAt', models.DateTimeField(auto_now_add=True, help_text='플레이 시간')),
                ('chart', models.ForeignKey(help_text='결과가 속한 차트', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.chart')),
                ('user', models.ForeignKey(help_text='결과를 기록한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='점수')),
                ('chart', models.ForeignKey(help_text='랭킹이 속한 차트', on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='game.chart')),
                ('user', models.ForeignKey(help_text='랭킹을 기록한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('chart', 'user')},
            },
        ),
    ]
