# Generated by Django 5.2.1 on 2025-12-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='bpm',
            field=models.IntegerField(default=120, help_text='BPM (분당 비트 수)'),
        ),
    ]
