# Generated by Django 5.2.1 on 2025-11-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='song',
            field=models.FileField(help_text='노래 음원 파일', upload_to='songs/'),
        ),
    ]
