# Generated by Django 5.2.1 on 2025-11-27 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='notes',
        ),
        migrations.AddField(
            model_name='note',
            name='chart',
            field=models.ForeignKey(blank=True, help_text='노트가 속한 차트', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='game.chart'),
        ),
    ]
