# Generated by Django 5.2.8 on 2025-12-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_chart_song'),
        ('game', '0002_chart_bpm'),
    ]

    operations = [
    ]
