# Generated by Django 5.2.8 on 2025-12-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_merge_0002_alter_chart_song_0002_chart_bpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='song',
            field=models.CharField(help_text='노래 음원 파일 경로', max_length=500),
        ),
    ]
